import { useState } from 'react';
import { Link } from '@tanstack/react-router';
import { Download, ShieldAlert, Plus, Check, ArrowUpRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { clients, deliverables, activity, demo, money } from '@/lib/proconta/demo';
import { useWorkspace } from '@/lib/proconta/context';
import { PageTitle, TableWrap, StatusBadge } from './shared';
import { Portfolio } from './portfolio';
import { downloadDemo } from './client-workspace';
export function ClientsPage(){const [form,setForm]=useState(false);const [done,setDone]=useState(false);return <><PageTitle title="Clientes" description="La cartera de tu despacho, en un solo lugar." actions={<Button onClick={()=>setForm(!form)}><Plus/>Nuevo cliente</Button>}/>{form&&<form className="client-form" onSubmit={e=>{e.preventDefault();setDone(true)}}><h2>Nuevo cliente · DEMO</h2><label className="field-label">Nombre del cliente<input required className="field" placeholder="Nombre ficticio"/></label><label className="field-label">Régimen<select className="field"><option>PF · 612</option><option>PF · 626</option><option>PM · 601</option></select></label><Button type="submit">Crear ficha DEMO</Button><Button variant="ghost" type="button" onClick={()=>setForm(false)}>Cancelar</Button>{done&&<p role="status" className="tone-success">Ficha simulada. El alta real estará disponible en una próxima versión.</p>}</form>}<Portfolio full/></>}
export function ProcessesPage(){return <><PageTitle title="Procesos" description="Estado de los servicios de cada cliente en el periodo."/><section className="data-section"><TableWrap><thead><tr><th>Cliente</th><th>Conciliación</th><th>IVA / ISR</th><th>Auxiliar</th><th>Emitidas</th><th>CxC</th><th/></tr></thead><tbody>{clients.map(c=><tr key={c.id}><td><strong>{c.name}</strong><small>{c.industry}</small></td>{c.statuses.map((s,i)=><td key={i}><StatusBadge status={s}/></td>)}<td><Button asChild variant="ghost" size="icon"><Link to="/clientes/$clientId" params={{clientId:c.id}} title="Abrir cliente"><ArrowUpRight/></Link></Button></td></tr>)}</tbody></TableWrap></section></>}
export function DeliverablesPage(){const {period}=useWorkspace();return <><PageTitle title="Entregables" description="Archivos listos para revisión y controles de salida."/><div className="attention-banner"><ShieldAlert size={22}/><div><strong>El control debe ser igual a cero</strong><p>Un control pendiente o con diferencia bloquea el entregable final.</p></div></div><section className="data-section"><TableWrap><thead><tr><th>Archivo</th><th>Cliente / Servicio</th><th>Periodo</th><th>Control</th><th>Estado</th><th>Fecha</th><th/></tr></thead><tbody>{deliverables.map(d=><tr key={d.name}><td><strong>{d.name}</strong><small>Entregable ficticio</small></td><td>{d.client}<small>{d.service}</small></td><td>{period}</td><td className={d.control!==0?'tone-danger numeric':'tone-success numeric'}>{d.control===null?'Pendiente':money(d.control)}</td><td><StatusBadge status={d.status}/></td><td>{d.date}</td><td><Button variant="outline" size="sm" disabled={d.control!==0} onClick={()=>downloadDemo(d.name)} title={d.control!==0?'Bloqueado por control':'Descargar muestra de texto DEMO'}><Download/>DEMO</Button></td></tr>)}</tbody></TableWrap></section></>}
export function HistoryPage(){return <><PageTitle title="Historial / Auditoría" description="Actividad y trazabilidad del espacio de trabajo."/><section className="data-section"><TableWrap><thead><tr><th>Actividad</th><th>Cliente / Servicio</th><th>Responsable</th><th>Fecha</th><th>Estado</th></tr></thead><tbody>{activity.map(a=><tr key={a.title}><td><strong>{a.title}</strong></td><td>{a.detail}</td><td>{a.initials==='ML'?demo.user:'ProConta DEMO'}</td><td>{a.time}</td><td><StatusBadge status="Completo"/></td></tr>)}</tbody></TableWrap></section></>}
export function SettingsPage(){const [saved,setSaved]=useState(false);const {firm}=useWorkspace();return <><PageTitle title="Configuración" description="Preferencias del despacho y del espacio de trabajo."/><form className="settings-form" onSubmit={e=>{e.preventDefault();setSaved(true)}}><h2>Datos del despacho</h2><label className="field-label">Nombre<input className="field" defaultValue={firm}/></label><label className="field-label">Moneda<select className="field"><option>MXN · Peso mexicano</option></select></label><label className="field-label">Usuario DEMO<input className="field" defaultValue={demo.user}/></label><div className="notice">Sin autenticación ni conexiones externas. Todas las preferencias son de demostración.</div><Button type="submit" className="mt-6"><Check/>Guardar preferencias DEMO</Button>{saved&&<p role="status" className="tone-success mt-4">Preferencias revisadas en esta sesión de demostración.</p>}</form></>}
