import type { ReactNode } from 'react';
import { CircleCheck, CircleAlert, Clock3, CircleDashed, LoaderCircle, LockKeyhole, ArrowUpRight, Search, SlidersHorizontal } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { type Status } from '@/lib/proconta/demo';
export function StatusBadge({status,compact=false}:{status:Status;compact?:boolean}) { const success=['Completo','Conciliado','Validado','Listo','Confirmado'].includes(status); const danger=['Bloqueado','Sin CFDI','Rechazado'].includes(status); const info=['Procesando','En revisión'].includes(status); const neutral=['No aplica','Pospuesto'].includes(status); const tone=success?'success':danger?'danger':info?'info':neutral?'neutral':'warning'; const Icon=success?CircleCheck:danger?LockKeyhole:status==='Procesando'?LoaderCircle:neutral?CircleDashed:status==='Pendiente'?Clock3:CircleAlert; return <span className={`status status-${tone} ${compact?'status-compact':''}`} title={status}><Icon size={13}/><span>{status}</span></span> }
export function PageTitle({eyebrow,title,description,actions}:{eyebrow?:string|undefined;title:string;description:string;actions?:ReactNode}) {return <div className="page-heading"><div>{eyebrow&&<div className="eyebrow">{eyebrow}</div>}<h1>{title}</h1><p>{description}</p></div><div className="heading-actions">{actions}</div></div>}
export function MetricCard({label,value,note,trend,kind='neutral',icon}:{label:string;value:string;note?:string;trend?:string;kind?:string;icon?:ReactNode}) {return <article className="metric-card"><div className="metric-label">{label}<span className={`metric-icon tone-${kind}`}>{icon||<ArrowUpRight size={16}/>}</span></div><div className="metric-value">{value}</div>{note&&<p>{note}</p>}{trend&&<div className={`metric-trend tone-${kind}`}>{kind==='success'?<CircleCheck size={12}/>:kind==='warning'||kind==='danger'?<CircleAlert size={12}/>:<ArrowUpRight size={12}/>} {trend}</div>}</article>}
export function TableWrap({children}:{children:ReactNode}) {return <div className="table-scroll"><table className="data-table">{children}</table></div>}
export function SearchInput({value,onChange,placeholder='Buscar…'}:{value:string;onChange:(s:string)=>void;placeholder?:string}) {return <div className="search-input"><Search size={16}/><input aria-label={placeholder} placeholder={placeholder} value={value} onChange={e=>onChange(e.target.value)}/></div>}
export function EmptyState({title='Sin resultados',description='No hay elementos que coincidan con tu búsqueda.'}:{title?:string;description?:string}) {return <div className="empty-state"><CircleDashed size={30}/><h3>{title}</h3><p>{description}</p></div>}
export function FilterButton({onClick,active=false}:{onClick:()=>void;active?:boolean}) {return <Button variant={active?'secondary':'outline'} onClick={onClick}><SlidersHorizontal/>Filtros{active&&<span className="filter-dot"/>}</Button>}
