export type Status = 'Completo' | 'Pendiente' | 'Procesando' | 'Observaciones' | 'Bloqueado' | 'Requiere decisión' | 'No aplica' | 'Conciliado' | 'Sin CFDI' | 'Parcial' | 'Validado' | 'Incompleto' | 'Listo' | 'Confirmado' | 'Rechazado' | 'En revisión' | 'Pospuesto';
export const demo = { firm: 'Despacho Contable Veracruz', period: 'Septiembre 2026', user: 'Mariana López', initials: 'ML', metrics: [{label:'Clientes activos',value:'24',note:'En la cartera del despacho',trend:'+2 este mes',kind:'neutral'}, {label:'Decisiones pendientes',value:'12',note:'Requieren tu criterio',trend:'5 prioritarias',kind:'warning'}, {label:'Documentos faltantes',value:'4',note:'En 3 clientes',trend:'Ver archivos',kind:'danger'}, {label:'Entregables listos',value:'8',note:'Con controles en cero',trend:'Listos para descargar',kind:'success'}, {label:'Controles con error',value:'2',note:'Entregables bloqueados',trend:'Requieren revisión',kind:'danger'}], activeCount:24, visibleCount:6, reconciliationMetrics:[{label:'Salidas analizadas',value:'140'},{label:'Conciliado',value:'85%'},{label:'Sin CFDI',value:'44'},{label:'Con observación',value:'7'},{label:'Parciales',value:'2'}], receivableMetrics:[{label:'Por cobrar',value:'$1,008,233'},{label:'Facturas abiertas',value:'87'},{label:'Clientes con saldo',value:'8'},{label:'Más de 90 días',value:'31%'}], aging:[{label:'0–30 días',value:'$382,128',width:100,tone:'success'},{label:'31–60 días',value:'$201,647',width:53,tone:'info'},{label:'61–90 días',value:'$111,906',width:29,tone:'warning'},{label:'90+ días',value:'$312,552',width:82,tone:'danger'}] };
export interface Client {id:string; name:string; industry:string; type:string; initials:string; tone:string; statuses:Status[]; pending:number; progress:number}
export const clients:Client[] = [
{id:'a',name:'Cliente A',industry:'Vidrio y aluminio',type:'PF · 612',initials:'CA',tone:'mint',statuses:['Observaciones','Requiere decisión','Completo','Completo','Pendiente'],pending:4,progress:72},
{id:'b',name:'Cliente B',industry:'Venta al público',type:'PF · 626',initials:'CB',tone:'blue',statuses:['Completo','Completo','Completo','Completo','No aplica'],pending:0,progress:100},
{id:'c',name:'Cliente C',industry:'Venta al público / IEPS',type:'PM · 601',initials:'CC',tone:'lavender',statuses:['Completo','Procesando','Pendiente','Completo','Pendiente'],pending:3,progress:56},
{id:'d',name:'Cliente D',industry:'Autotransporte',type:'PM · 624',initials:'CD',tone:'peach',statuses:['Bloqueado','Pendiente','Pendiente','Completo','Observaciones'],pending:3,progress:38},
{id:'e',name:'Cliente E',industry:'Servicios profesionales',type:'PF · 612',initials:'CE',tone:'blue',statuses:['Completo','Completo','Completo','Completo','Completo'],pending:0,progress:100},
{id:'f',name:'Cliente F',industry:'Comercializadora',type:'PM · 601',initials:'CF',tone:'mint',statuses:['Completo','Observaciones','Completo','Completo','Pendiente'],pending:2,progress:81}
];
export const decisions = [
{id:1,client:'Cliente A',service:'IVA / ISR',title:'Préstamos recibidos sin contrato',amount:82000,priority:'Alta',confidence:'92%',explanation:'Se detectaron dos depósitos identificados como préstamo sin un contrato en los archivos del periodo.',proposal:'Solicitar el contrato antes de confirmar el tratamiento de los depósitos.',question:'¿Existe un contrato que respalde los préstamos?',evidence:['Depósito · 12/09/2026 · $50,000.00','Depósito · 19/09/2026 · $32,000.00']},
{id:2,client:'Cliente A',service:'Conciliación',title:'Gasto sin CFDI relacionado',amount:12450,priority:'Alta',confidence:'87%',explanation:'La salida bancaria no tiene una factura relacionada entre los CFDI recibidos.',proposal:'Solicitar el CFDI al proveedor y mantener el movimiento en revisión.',question:'¿Se cuenta con una factura para este gasto?',evidence:['Transferencia · 23/09/2026 · $12,450.00']},
{id:3,client:'Cliente C',service:'IVA / ISR',title:'Clasificación de operación con IEPS',amount:18600,priority:'Media',confidence:'78%',explanation:'El concepto de la factura requiere validar su clasificación con el contador.',proposal:'Revisar la evidencia y confirmar el criterio aplicable.',question:'¿Confirmas la clasificación de esta operación?',evidence:['CFDI DEMO · F-0093 · $18,600.00']},
{id:4,client:'Cliente D',service:'Auxiliar',title:'Diferencia en el control del auxiliar',amount:2350,priority:'Alta',confidence:'96%',explanation:'El control del auxiliar presenta una diferencia respecto al resumen del periodo.',proposal:'Revisar los registros antes de liberar el entregable.',question:'¿Qué ajuste debe revisarse para resolver la diferencia?',evidence:['Control auxiliar · Diferencia $2,350.00']}
];
export const movements = [
{id:1,date:'02 sep 2026',description:'SPEI FERRETERÍA DEL GOLFO',provider:'Ferretería del Golfo',amount:8450,cfdi:'F-2034',difference:0,status:'Conciliado' as Status,observation:'Importe y proveedor coinciden',confidence:'99%'},
{id:2,date:'05 sep 2026',description:'PAGO SERVICIOS INTERNET',provider:'Servicios de telecomunicaciones',amount:899,cfdi:'F-1082',difference:0,status:'Conciliado' as Status,observation:'Coincidencia completa',confidence:'98%'},
{id:3,date:'12 sep 2026',description:'TRANSFERENCIA PROVEEDOR',provider:'Aluminios del Sureste',amount:12450,cfdi:'—',difference:12450,status:'Sin CFDI' as Status,observation:'Factura pendiente de recibir',confidence:'87%'},
{id:4,date:'15 sep 2026',description:'COMPRA MATERIAL VIDRIO',provider:'Distribuidora de Vidrio',amount:16300,cfdi:'F-3108',difference:300,status:'Observaciones' as Status,observation:'Diferencia en el importe',confidence:'91%'},
{id:5,date:'19 sep 2026',description:'PAGO PARCIAL EQUIPO',provider:'Equipos Industriales',amount:5800,cfdi:'F-4002',difference:5800,status:'Parcial' as Status,observation:'Pago parcial identificado',confidence:'94%'},
{id:6,date:'23 sep 2026',description:'COMISIÓN BANCARIA',provider:'BBVA',amount:185,cfdi:'—',difference:0,status:'No aplica' as Status,observation:'Revisión del criterio requerida',confidence:'95%'}
];
export const files = [
{id:1,name:'movimientos_bbva_pyme_sep.xlsx',category:'Movimientos bancarios',format:'BBVA XLS',cutoff:'26/09/2026',rows:140,status:'Validado' as Status,note:'Estructura y periodo correctos'},
{id:2,name:'cfdi_recibidos_sep.zip',category:'CFDI recibidos',format:'XML / ZIP',cutoff:'30/09/2026',rows:96,status:'Validado' as Status,note:'Sin observaciones'},
{id:3,name:'cfdi_emitidos_sep.zip',category:'CFDI emitidos',format:'XML / ZIP',cutoff:'30/09/2026',rows:87,status:'Validado' as Status,note:'Sin observaciones'},
{id:4,name:'tarjeta_bbva_sep.xlsx',category:'Tarjetas',format:'BBVA XLS',cutoff:'26/09/2026',rows:3,status:'Incompleto' as Status,note:'Solo se detectaron 3 movimientos.'},
{id:5,name:'auxiliar_contable_sep.xlsx',category:'Auxiliar contable',format:'XLSX',cutoff:'30/09/2026',rows:248,status:'Observaciones' as Status,note:'Diferencia de control por revisar'}
];
export const receivables = [ {name:'Comprador DEMO 01',balance:312552,invoices:18,age:'90+ días',last:'12 jun 2026',status:'Observaciones' as Status},{name:'Comprador DEMO 02',balance:201647,invoices:14,age:'31–60 días',last:'18 ago 2026',status:'Pendiente' as Status},{name:'Comprador DEMO 03',balance:185320,invoices:22,age:'0–30 días',last:'22 sep 2026',status:'Completo' as Status},{name:'Comprador DEMO 04',balance:111906,invoices:9,age:'61–90 días',last:'04 jul 2026',status:'Observaciones' as Status},{name:'Comprador DEMO 05',balance:196808,invoices:24,age:'0–30 días',last:'25 sep 2026',status:'Completo' as Status} ];
export const deliverables = [{name:'Cta_por_Cobrar_20260917.xlsx',client:'Cliente A',service:'Cuentas por cobrar',control:0,status:'Listo' as Status,date:'30 sep 2026'},{name:'Conciliacion_A_2026_09.xlsx',client:'Cliente A',service:'Conciliación',control:null,status:'Bloqueado' as Status,date:'30 sep 2026'},{name:'Auxiliar_D_2026_09.xlsx',client:'Cliente D',service:'Auxiliar',control:2350,status:'Bloqueado' as Status,date:'29 sep 2026'}];
export const activity = [{initials:'ML',title:'Mariana confirmó un criterio',detail:'Cliente B · IVA / ISR',time:'Hace 15 min',type:'success'},{initials:'PC',title:'Conciliación completada',detail:'Cliente E · Septiembre 2026',time:'Hace 42 min',type:'info'},{initials:'ML',title:'Se agregaron 96 CFDI recibidos',detail:'Cliente A · Archivos',time:'Hace 1 h',type:'neutral'}];
export const money = (n:number) => new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(n);
