/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchivosRouteImport } from './routes/archivos'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ConciliacionRouteImport } from './routes/conciliacion'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as CuentasPorCobrarRouteImport } from './routes/cuentas-por-cobrar'
import { Route as DecisionesRouteImport } from './routes/decisiones'
import { Route as EntregablesRouteImport } from './routes/entregables'
import { Route as HistorialRouteImport } from './routes/historial'
import { Route as IvaIsrRouteImport } from './routes/iva-isr'
import { Route as ProcesosRouteImport } from './routes/procesos'
import { Route as SalidasVsCfdiRouteImport } from './routes/salidas-vs-cfdi'
import { Route as ClientesIndexRouteImport } from './routes/clientes.index'
import { Route as ClientesClientIdRouteImport } from './routes/clientes.$clientId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivosRoute = ArchivosRouteImport.update({
  id: '/archivos',
  path: '/archivos',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConciliacionRoute = ConciliacionRouteImport.update({
  id: '/conciliacion',
  path: '/conciliacion',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const CuentasPorCobrarRoute = CuentasPorCobrarRouteImport.update({
  id: '/cuentas-por-cobrar',
  path: '/cuentas-por-cobrar',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionesRoute = DecisionesRouteImport.update({
  id: '/decisiones',
  path: '/decisiones',
  getParentRoute: () => rootRouteImport,
} as any)
const EntregablesRoute = EntregablesRouteImport.update({
  id: '/entregables',
  path: '/entregables',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorialRoute = HistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => rootRouteImport,
} as any)
const IvaIsrRoute = IvaIsrRouteImport.update({
  id: '/iva-isr',
  path: '/iva-isr',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcesosRoute = ProcesosRouteImport.update({
  id: '/procesos',
  path: '/procesos',
  getParentRoute: () => rootRouteImport,
} as any)
const SalidasVsCfdiRoute = SalidasVsCfdiRouteImport.update({
  id: '/salidas-vs-cfdi',
  path: '/salidas-vs-cfdi',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientesRoute,
} as any)
const ClientesClientIdRoute = ClientesClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => ClientesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archivos': typeof ArchivosRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/conciliacion': typeof ConciliacionRoute
  '/configuracion': typeof ConfiguracionRoute
  '/cuentas-por-cobrar': typeof CuentasPorCobrarRoute
  '/decisiones': typeof DecisionesRoute
  '/entregables': typeof EntregablesRoute
  '/historial': typeof HistorialRoute
  '/iva-isr': typeof IvaIsrRoute
  '/procesos': typeof ProcesosRoute
  '/salidas-vs-cfdi': typeof SalidasVsCfdiRoute
  '/clientes/$clientId': typeof ClientesClientIdRoute
  '/clientes/': typeof ClientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archivos': typeof ArchivosRoute
  '/conciliacion': typeof ConciliacionRoute
  '/configuracion': typeof ConfiguracionRoute
  '/cuentas-por-cobrar': typeof CuentasPorCobrarRoute
  '/decisiones': typeof DecisionesRoute
  '/entregables': typeof EntregablesRoute
  '/historial': typeof HistorialRoute
  '/iva-isr': typeof IvaIsrRoute
  '/procesos': typeof ProcesosRoute
  '/salidas-vs-cfdi': typeof SalidasVsCfdiRoute
  '/clientes/$clientId': typeof ClientesClientIdRoute
  '/clientes': typeof ClientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archivos': typeof ArchivosRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/conciliacion': typeof ConciliacionRoute
  '/configuracion': typeof ConfiguracionRoute
  '/cuentas-por-cobrar': typeof CuentasPorCobrarRoute
  '/decisiones': typeof DecisionesRoute
  '/entregables': typeof EntregablesRoute
  '/historial': typeof HistorialRoute
  '/iva-isr': typeof IvaIsrRoute
  '/procesos': typeof ProcesosRoute
  '/salidas-vs-cfdi': typeof SalidasVsCfdiRoute
  '/clientes/$clientId': typeof ClientesClientIdRoute
  '/clientes/': typeof ClientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archivos'
    | '/clientes'
    | '/conciliacion'
    | '/configuracion'
    | '/cuentas-por-cobrar'
    | '/decisiones'
    | '/entregables'
    | '/historial'
    | '/iva-isr'
    | '/procesos'
    | '/salidas-vs-cfdi'
    | '/clientes/$clientId'
    | '/clientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archivos'
    | '/conciliacion'
    | '/configuracion'
    | '/cuentas-por-cobrar'
    | '/decisiones'
    | '/entregables'
    | '/historial'
    | '/iva-isr'
    | '/procesos'
    | '/salidas-vs-cfdi'
    | '/clientes/$clientId'
    | '/clientes'
  id:
    | '__root__'
    | '/'
    | '/archivos'
    | '/clientes'
    | '/conciliacion'
    | '/configuracion'
    | '/cuentas-por-cobrar'
    | '/decisiones'
    | '/entregables'
    | '/historial'
    | '/iva-isr'
    | '/procesos'
    | '/salidas-vs-cfdi'
    | '/clientes/$clientId'
    | '/clientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchivosRoute: typeof ArchivosRoute
  ClientesRoute: typeof ClientesRouteWithChildren
  ConciliacionRoute: typeof ConciliacionRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  CuentasPorCobrarRoute: typeof CuentasPorCobrarRoute
  DecisionesRoute: typeof DecisionesRoute
  EntregablesRoute: typeof EntregablesRoute
  HistorialRoute: typeof HistorialRoute
  IvaIsrRoute: typeof IvaIsrRoute
  ProcesosRoute: typeof ProcesosRoute
  SalidasVsCfdiRoute: typeof SalidasVsCfdiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archivos': {
      id: '/archivos'
      path: '/archivos'
      fullPath: '/archivos'
      preLoaderRoute: typeof ArchivosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conciliacion': {
      id: '/conciliacion'
      path: '/conciliacion'
      fullPath: '/conciliacion'
      preLoaderRoute: typeof ConciliacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuentas-por-cobrar': {
      id: '/cuentas-por-cobrar'
      path: '/cuentas-por-cobrar'
      fullPath: '/cuentas-por-cobrar'
      preLoaderRoute: typeof CuentasPorCobrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisiones': {
      id: '/decisiones'
      path: '/decisiones'
      fullPath: '/decisiones'
      preLoaderRoute: typeof DecisionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entregables': {
      id: '/entregables'
      path: '/entregables'
      fullPath: '/entregables'
      preLoaderRoute: typeof EntregablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historial': {
      id: '/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof HistorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iva-isr': {
      id: '/iva-isr'
      path: '/iva-isr'
      fullPath: '/iva-isr'
      preLoaderRoute: typeof IvaIsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procesos': {
      id: '/procesos'
      path: '/procesos'
      fullPath: '/procesos'
      preLoaderRoute: typeof ProcesosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salidas-vs-cfdi': {
      id: '/salidas-vs-cfdi'
      path: '/salidas-vs-cfdi'
      fullPath: '/salidas-vs-cfdi'
      preLoaderRoute: typeof SalidasVsCfdiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof ClientesRoute
    }
    '/clientes/$clientId': {
      id: '/clientes/$clientId'
      path: '/$clientId'
      fullPath: '/clientes/$clientId'
      preLoaderRoute: typeof ClientesClientIdRouteImport
      parentRoute: typeof ClientesRoute
    }
  }
}

interface ClientesRouteChildren {
  ClientesClientIdRoute: typeof ClientesClientIdRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
}

const ClientesRouteChildren: ClientesRouteChildren = {
  ClientesClientIdRoute: ClientesClientIdRoute,
  ClientesIndexRoute: ClientesIndexRoute,
}

const ClientesRouteWithChildren = ClientesRoute._addFileChildren(
  ClientesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchivosRoute: ArchivosRoute,
  ClientesRoute: ClientesRouteWithChildren,
  ConciliacionRoute: ConciliacionRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  CuentasPorCobrarRoute: CuentasPorCobrarRoute,
  DecisionesRoute: DecisionesRoute,
  EntregablesRoute: EntregablesRoute,
  HistorialRoute: HistorialRoute,
  IvaIsrRoute: IvaIsrRoute,
  ProcesosRoute: ProcesosRoute,
  SalidasVsCfdiRoute: SalidasVsCfdiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
